server:
  port: 8080
torrent:
  peer-id:
    prefix: -PR0001-
    suffix-length: 12

spring:
  data:
    mongodb:
      uri: mongodb://back:back@localhost:27017/db?authSource=admin
      authentication-database: admin
      database: db

validation:
  torrent:
    invalid: invalid-torrent-file
    exists: torrent-already-exists
  tracker:
    scheme: no-supported-scheme-provided
  unknown: internal-server-error
